### ISSUE TITLE
Project Scaffolding

### ISSUE THREAD

**Issue by rodcul** [rodcul/12questions#1]
- Sinatra/Padrino/Other?
- Database
- Frontend (bootstrap?)
- Testing framework

**Comment by rodcul** [comment]
I am getting this error on shotgun (but it works if I run "bundle exec rackup"

Boot Error

Something went wrong while loading config.ru

Gem::LoadError: You have already activated rack 1.6.1, but your Gemfile requires rack 1.5.3. Prepending `bundle exec` to your command may solve this.

/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.6/lib/bundler/runtime.rb:34:in `block in setup'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.6/lib/bundler/runtime.rb:19:in `setup'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.6/lib/bundler.rb:122:in `setup'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/bundler-1.9.6/lib/bundler/setup.rb:8:in `<top (required)>'
/Users/rodcul/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/rodcul/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/rodcul/dev/makers-academy/12questions/config/boot.rb:7:in `<top (required)>'
/Users/rodcul/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/rodcul/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
config.ru:7:in `block in inner_app'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/builder.rb:55:in `instance_eval'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `inner_app'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:113:in `eval'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:113:in `inner_app'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:103:in `assemble_app'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/favicon.rb:12:in `call'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/static.rb:14:in `call'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/urlmap.rb:66:in `block in call'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/urlmap.rb:50:in `each'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/urlmap.rb:50:in `call'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/builder.rb:153:in `call'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/handler/thin.rb:19:in `run'
/Users/rodcul/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/bin/shotgun:162:in `<top (required)>'
/Users/rodcul/.rvm/gems/ruby-2.2.1/bin/shotgun:23:in `load'
/Users/rodcul/.rvm/gems/ruby-2.2.1/bin/shotgun:23:in `<main>'
/Users/rodcul/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/rodcul/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by DanielJohnston** [comment]
Also needs capybara installed.
